/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  specSidebar: [
    {
      type: 'doc',
      id: 'meta/document-control',
      label: '📋 Document Control',
    },
    {
      type: 'category',
      label: 'Volume 0 — Meta',
      collapsed: false,
      items: [
        'meta/engineering-knowledge-base',
        'meta/engineering-standards',
        'meta/cursor-implementation-workflow',
        'meta/task-specification-template',
        'meta/module-template',
        'meta/implementation-knowledge-graph',
        'meta/architect-ai-governance',
        'meta/legacy-capability-matrix',
        'meta/engineering-principles',
        'meta/research-and-synthesis-program',
        'meta/synthesis-status',
        'meta/glossary',
        {
          type: 'category',
          label: 'Architecture Decision Records',
          items: [
            'meta/adr/template',
            'meta/adr/modular-monolith-over-microservices',
            'meta/adr/multi-tenancy-shared-db-rls',
            'meta/adr/theme-engine-react-json-schema',
            'meta/adr/checkout-psp-redirect-saq-a',
            'meta/adr/rls-pgbouncer-set-local',
            'meta/adr/authentication-stack',
            'meta/adr/secrets-management',
            'meta/adr/edge-security-cloudflare',
            'meta/adr/audit-log-immutability',
            'meta/adr/admin-impersonation',
            'meta/adr/data-residency-africa',
            'meta/adr/hybrid-cms-theme-sections-content-types',
            'meta/adr/blocknote-canonical-rich-text',
            'meta/adr/release-based-content-scheduling',
            'meta/adr/hybrid-localization-model',
            'meta/adr/learning-as-catalog-extension',
            'meta/adr/three-system-storefront-architecture',
            'meta/adr/adaptive-storefront-intelligence',
            'meta/adr/financial-services-layer',
            'meta/adr/sapphital-intelligence-platform',
            'meta/adr/ai-guided-merchant-onboarding',
            'meta/adr/tenant-provisioning-engine',
            'meta/adr/sapphital-platform-os',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Volume 1 — Vision & Product Strategy',
      collapsed: false,
      link: { type: 'doc', id: 'vision/README' },
      items: [
        'vision/mission-and-vision',
        'vision/problem-statement',
        'vision/target-markets',
        'vision/product-principles',
        'vision/user-personas',
        'vision/competitive-positioning',
        'vision/success-metrics',
        'vision/product-roadmap',
        'vision/non-functional-requirements',
        'vision/domain-model-overview',
      ],
    },
    {
      type: 'category',
      label: 'Volume 2 — Market Research',
      collapsed: true,
      link: { type: 'doc', id: 'market-research/README' },
      items: [
        'market-research/commerce-landscape-2026',
        'market-research/competitive-analysis-global-platforms',
        'market-research/competitive-analysis-africa-nigeria',
        'market-research/payment-fintech-strategy',
        'market-research/technology-evaluation-framework',
        'market-research/backend-frontend-stack-decisions',
        'market-research/data-search-caching-storage',
        'market-research/ai-commerce-market-opportunity',
        'market-research/strategic-positioning-and-differentiation',
        'market-research/technology-roadmap-and-risks',
      ],
    },
    {
      type: 'category',
      label: 'Volume 3 — Architecture',
      collapsed: true,
      link: { type: 'doc', id: 'architecture/README' },
      items: [
        'architecture/architecture-overview',
        'architecture/architectural-principles-and-constraints',
        'architecture/bounded-contexts-and-modules',
        'architecture/clean-architecture-layers',
        'architecture/multi-tenancy-and-isolation',
        'architecture/request-lifecycle-and-auth',
        'architecture/event-driven-communication',
        'architecture/api-architecture-and-versioning',
        'architecture/data-ownership-and-contracts',
        'architecture/extensibility-themes-plugins-webhooks',
        'architecture/scalability-and-service-extraction',
        'architecture/deployment-and-runtime-topology',
        'architecture/platform-os-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Volume 4 — Design System',
      collapsed: true,
      link: { type: 'doc', id: 'design-system/README' },
      items: [
        'design-system/design-philosophy-and-principles',
        'design-system/design-tokens',
        'design-system/typography-and-iconography',
        'design-system/color-elevation-motion',
        'design-system/component-architecture',
        'design-system/core-component-inventory',
        'design-system/admin-and-merchant-dashboard-ux',
        'design-system/storefront-and-checkout-ux',
        'design-system/accessibility-wcag-22',
        'design-system/theme-inheritance-and-customization',
        'design-system/design-governance-figma-storybook',
        'design-system/performance-and-ux-budgets',
        'design-system/storefront-visual-direction',
        'design-system/intelligent-homepage-customer-portal',
        'design-system/ai-guided-onboarding-ux',
      ],
    },
    {
      type: 'category',
      label: 'Volume 5 — Commerce Engine',
      collapsed: true,
      link: { type: 'doc', id: 'commerce-engine/README' },
      items: [
        'commerce-engine/catalog-and-products',
        'commerce-engine/variants-attributes-pricing',
        'commerce-engine/collections-and-categories',
        'commerce-engine/inventory-and-warehouses',
        'commerce-engine/cart-and-session',
        'commerce-engine/checkout-architecture',
        'commerce-engine/orders-and-fulfillment',
        'commerce-engine/payments-nigeria-africa',
        'commerce-engine/taxes-and-compliance',
        'commerce-engine/shipping-and-logistics',
        'commerce-engine/promotions-discounts-coupons',
        'commerce-engine/returns-refunds-disputes',
        'commerce-engine/subscriptions-and-gift-cards',
        'commerce-engine/digital-products-and-services',
        'commerce-engine/community-loyalty-live-commerce',
        'commerce-engine/financial-services-layer',
        'commerce-engine/payment-gateway-adapters-africa',
        'commerce-engine/regional-engines-currency-tax-language',
        'commerce-engine/offline-payments-mobile-money-ux',
        'commerce-engine/promotional-campaigns-and-flash-sales',
        'commerce-engine/catalog-operations-compare-clone-badges',
        'commerce-engine/bookings-and-service-commerce',
      ],
    },
    {
      type: 'category',
      label: 'Volume 6 — Theme Engine',
      collapsed: true,
      link: { type: 'doc', id: 'theme-engine/README' },
      items: [
        'theme-engine/theme-engine-overview',
        'theme-engine/template-schema-specification',
        'theme-engine/sections-blocks-app-blocks',
        'theme-engine/rendering-pipeline-rsc',
        'theme-engine/theme-editor-merchant-ux',
        'theme-engine/theme-sdk-and-cli',
        'theme-engine/theme-marketplace',
        'theme-engine/assets-and-performance',
        'theme-engine/security-sandbox-csp',
        'theme-engine/migration-and-versioning',
        'theme-engine/reference-themes-section-catalog',
        'theme-engine/storefront-engine-eight-layers',
        'theme-engine/runtime-visual-builder-separation',
        'theme-engine/storefront-performance-engine',
      ],
    },
    {
      type: 'category',
      label: 'Volume 7 — CMS & Page Builder',
      collapsed: true,
      link: { type: 'doc', id: 'cms/README' },
      items: [
        'cms/cms-overview',
        'cms/content-model',
        'cms/page-builder-architecture',
        'cms/block-library',
        'cms/editor-ux-workflows',
        'cms/seo-and-metadata',
        'cms/blog-and-navigation',
        'cms/media-library',
        'cms/education-commerce-pages',
        'cms/api-events-security',
        'cms/forms-and-lead-capture',
      ],
    },
    {
      type: 'category',
      label: 'Volume 8 — Marketplace',
      collapsed: true,
      link: { type: 'doc', id: 'marketplace/README' },
      items: [
        'marketplace/marketplace-overview',
        'marketplace/vendor-onboarding-kyc',
        'marketplace/vendor-dashboard',
        'marketplace/commissions-and-fees',
        'marketplace/split-payments-payouts-nigeria',
        'marketplace/disputes-trust-safety',
        'marketplace/multi-vendor-catalog',
        'marketplace/vendor-analytics',
        'marketplace/state-machines',
        'marketplace/api-events',
        'marketplace/compliance-tax',
        'marketplace/acceptance-criteria',
      ],
    },
    {
      type: 'category',
      label: 'Volume 9 — AI Platform',
      collapsed: true,
      link: { type: 'doc', id: 'ai-platform/README' },
      items: [
        'ai-platform/ai-platform-overview',
        'ai-platform/model-gateway',
        'ai-platform/rag-pgvector',
        'ai-platform/agent-orchestration',
        'ai-platform/shopping-assistant-agent',
        'ai-platform/merchant-ops-agent',
        'ai-platform/support-agent',
        'ai-platform/marketing-inventory-agents',
        'ai-platform/safety-moderation',
        'ai-platform/tenant-isolation-cost-controls',
        'ai-platform/dpia-compliance-ndpa',
        'ai-platform/ai-storefront-commerce',
        'ai-platform/adaptive-storefront-intelligence',
        'ai-platform/ai-theme-generator',
        'ai-platform/africa-commerce-ai-advisor',
        'ai-platform/ai-operating-system-architecture',
        'ai-platform/ai-memory-knowledge-business-graph',
        'ai-platform/ai-agents-skills-multi-agent',
        'ai-platform/ai-workflow-engine-event-bus',
        'ai-platform/ai-observability-prompts-security-learning',
        'ai-platform/advanced-ai-capabilities',
        'ai-platform/acceptance-criteria',
      ],
    },
    {
      type: 'category',
      label: 'Volume 10 — Infrastructure',
      collapsed: true,
      link: { type: 'doc', id: 'infrastructure/README' },
      items: [
        'infrastructure/infrastructure-overview',
        'infrastructure/cloud-architecture-nigeria-africa',
        'infrastructure/compute-frankenphp-octane',
        'infrastructure/postgresql-redis-meilisearch',
        'infrastructure/storage-cdn-cloudflare',
        'infrastructure/ci-cd-pipeline',
        'infrastructure/environments-and-config',
        'infrastructure/monitoring-observability',
        'infrastructure/backup-disaster-recovery',
        'infrastructure/scaling-path-kubernetes',
        'infrastructure/cost-models',
        'infrastructure/runbooks',
      ],
    },
    {
      type: 'category',
      label: 'Volume 11 — Security',
      collapsed: true,
      link: { type: 'doc', id: 'security/README' },
      items: [
        'security/compliance-framework',
        'security/africa-regulatory-compliance',
        'security/threat-model',
        'security/security-architecture',
        'security/security-testing',
        'security/incident-response',
        'security/acceptance-criteria',
      ],
    },
    {
      type: 'category',
      label: 'Volume 12 — Developer Platform',
      collapsed: true,
      link: { type: 'doc', id: 'developer-platform/README' },
      items: [
        'developer-platform/developer-platform-overview',
        'developer-platform/api-design-standards',
        'developer-platform/rest-api-specification',
        'developer-platform/webhooks-and-events',
        'developer-platform/authentication-oauth-scopes',
        'developer-platform/sdks-php-js',
        'developer-platform/plugin-runtime',
        'developer-platform/theme-app-extensions',
        'developer-platform/cli-scp-tool',
        'developer-platform/app-review-marketplace',
        'developer-platform/security-ssrf-rate-limits',
      ],
    },
    {
      type: 'category',
      label: 'Volume 13 — Testing',
      collapsed: true,
      link: { type: 'doc', id: 'testing/README' },
      items: [
        'testing/testing-strategy-overview',
        'testing/testing-pyramid',
        'testing/unit-integration-tests',
        'testing/tenant-isolation-test-suite',
        'testing/e2e-playwright',
        'testing/performance-k6-lighthouse',
        'testing/security-testing',
        'testing/accessibility-testing',
        'testing/ci-quality-gates',
        'testing/release-criteria',
      ],
    },
    {
      type: 'category',
      label: 'Volume 14 — Operations',
      collapsed: true,
      link: { type: 'doc', id: 'operations/README' },
      items: [
        'operations/operations-overview',
        'operations/slo-sla-error-budgets',
        'operations/incident-management',
        'operations/on-call-escalation',
        'operations/capacity-planning',
        'operations/database-operations',
        'operations/merchant-support-operations',
        'operations/status-page-communications',
        'operations/postmortems',
        'operations/operations-acceptance-criteria',
        'operations/database-analytics-architecture',
        'operations/merchant-storefront-analytics',
      ],
    },
    {
      type: 'category',
      label: 'Volume 15 — Future Roadmap',
      collapsed: true,
      link: { type: 'doc', id: 'future-roadmap/README' },
      items: [
        'future-roadmap/roadmap-overview',
        'future-roadmap/mobile-react-native',
        'future-roadmap/pos-omnichannel',
        'future-roadmap/erp-crm-integrations',
        'future-roadmap/west-africa-expansion',
        'future-roadmap/enterprise-tier',
        'future-roadmap/global-expansion-gdpr',
        'future-roadmap/platform-vision-2030',
        'future-roadmap/pos-module-specification',
        'future-roadmap/mobile-app-architecture',
        'future-roadmap/erp-integration-deep-dive',
        'future-roadmap/sapphital-academy-integration',
        'future-roadmap/global-expansion-strategy',
        'future-roadmap/enterprise-features-roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Volume 16 — SaaS & Multi-Tenancy',
      collapsed: true,
      link: { type: 'doc', id: 'saas-multi-tenancy/README' },
      items: [
        'saas-multi-tenancy/saas-overview',
        'saas-multi-tenancy/tenant-lifecycle',
        'saas-multi-tenancy/plans-and-entitlements',
        'saas-multi-tenancy/billing-and-invoicing',
        'saas-multi-tenancy/usage-metering',
        'saas-multi-tenancy/feature-flags',
        'saas-multi-tenancy/custom-domains',
        'saas-multi-tenancy/saas-acceptance-criteria',
        'saas-multi-tenancy/ai-guided-merchant-onboarding',
        'saas-multi-tenancy/tenant-provisioning-engine',
        'saas-multi-tenancy/platform-admin-operator-guide',
        'saas-multi-tenancy/platform-marketing-site-and-signup',
        'saas-multi-tenancy/platform-plan-coupons-and-trials',
        'saas-multi-tenancy/localization-admin-and-translations',
      ],
    },
    {
      type: 'category',
      label: 'Volume 17 — Database & Data Architecture',
      collapsed: true,
      link: { type: 'doc', id: 'database-data-architecture/README' },
      items: [
        'database-data-architecture/database-architecture-overview',
        'database-data-architecture/postgresql-schema-design',
        'database-data-architecture/row-level-security-policies',
        'database-data-architecture/indexing-partitioning-strategy',
        'database-data-architecture/migrations-zero-downtime',
        'database-data-architecture/event-outbox-audit-tables',
        'database-data-architecture/read-replicas-caching',
        'database-data-architecture/analytics-pipeline-olap',
        'database-data-architecture/materialized-views-reporting',
        'database-data-architecture/backup-retention-archival',
        'database-data-architecture/data-governance-ndpa',
        'database-data-architecture/database-acceptance-criteria',
      ],
    },
    {
      type: 'category',
      label: 'Volume 18 — Mobile & POS',
      collapsed: true,
      link: { type: 'doc', id: 'mobile-pos/README' },
      items: [
        'mobile-pos/mobile-pos-overview',
        'mobile-pos/react-native-architecture',
        'mobile-pos/customer-shopping-app',
        'mobile-pos/merchant-admin-app',
        'mobile-pos/pos-architecture',
        'mobile-pos/offline-sync-model',
        'mobile-pos/hardware-integrations',
        'mobile-pos/payments-at-pos-nigeria',
        'mobile-pos/security-ndpa-mobile',
        'mobile-pos/mobile-pos-acceptance-criteria',
        'mobile-pos/mobile-app-store-configuration',
        'mobile-pos/pos-hold-and-park-orders',
      ],
    },
    {
      type: 'category',
      label: 'Volume 19 — Automation & Integrations',
      collapsed: true,
      link: { type: 'doc', id: 'automation-integrations/README' },
      items: [
        'automation-integrations/automation-overview',
        'automation-integrations/workflow-engine',
        'automation-integrations/event-action-catalog',
        'automation-integrations/marketing-automation',
        'automation-integrations/crm-lite',
        'automation-integrations/erp-accounting-connectors',
        'automation-integrations/whatsapp-sms-channels',
        'automation-integrations/integration-marketplace',
        'automation-integrations/automation-security',
        'automation-integrations/automation-acceptance-criteria',
        'automation-integrations/merchant-integrations-hub',
        'automation-integrations/woocommerce-migration-connector',
      ],
    },
    {
      type: 'category',
      label: 'Volume 20 — Legal & Enterprise',
      collapsed: true,
      link: { type: 'doc', id: 'legal-enterprise/README' },
      items: [
        'legal-enterprise/legal-compliance-overview',
        'legal-enterprise/terms-privacy-dpa-templates',
        'legal-enterprise/ndpa-gaid-compliance-program',
        'legal-enterprise/kenya-ghana-expansion-legal',
        'legal-enterprise/gdpr-enterprise-readiness',
        'legal-enterprise/soc2-iso-roadmap',
        'legal-enterprise/enterprise-sla-contracts',
        'legal-enterprise/vendor-processor-agreements',
        'legal-enterprise/legal-acceptance-criteria',
        'legal-enterprise/regulatory-change-management',
      ],
    },
    {
      type: 'category',
      label: 'Volume 21 — Implementation Playbooks',
      collapsed: true,
      link: { type: 'doc', id: 'implementation-playbooks/README' },
      items: [
        'implementation-playbooks/master-execution-plan',
        'implementation-playbooks/implementation-overview',
        'implementation-playbooks/phase1-foundation-playbook',
        'implementation-playbooks/phase1-commerce-core-playbook',
        'implementation-playbooks/phase1-storefront-theme-playbook',
        'implementation-playbooks/phase1-payments-nigeria-playbook',
        'implementation-playbooks/phase1-security-compliance-playbook',
        'implementation-playbooks/phase2-growth-playbook',
        'implementation-playbooks/phase3-platform-marketplace-playbook',
        'implementation-playbooks/engineering-standards-checklist',
        'implementation-playbooks/onboarding-user-journeys',
        'implementation-playbooks/team-structure-hiring',
        'implementation-playbooks/launch-readiness-checklist',
      ],
    },
  ],
};

module.exports = sidebars;
